export const SET_CHANNEL_TITLE = 'SET_CHANNEL_TITLE'
export const SET_CHANNEL_DESC = 'SET_CHANNEL_DESC'
export const SET_CHANNEL_TAG = 'SET_CHANNEL_TAG'
export const SET_CHANNEL_PASSWORD = 'SET_CHANNEL_PASSWORD'
